ConvertFrom-StringData -StringData @'
    EnterLocalAdministratorPassword   = Enter the virtual machines' local administrator password.
    ExpandingIsoResource              = Expanding ISO resource '{0}'.
    SkippingIsoResource               = Skipping ISO resource '{0}'.
    ExpandingZipArchive               = Expanding Zip archive '{0}'.
    SkippingZipArchive                = Skipping Zip archive '{0}'.
    RemovingStaleResource             = Removing stale resource '{0}'.
    CopyingFileResource               = Copying file resource '{0}'.
    SkippingFileResource              = Skipping file resource '{0}'.
    CopyingExpandingResources         = Copying/expanding resource '{0}' to '{1}'.
    CopyingCertificate                = Copying certificate '{0}' to '{1}'.
    CopyingConfigurationDataFile      = Copying configuration data file '{0}'.
    CopyingConfigurationFile          = Copying configuration '{0}' to '{1}'.
    CopyingReadMeFile                 = Copying readme '{0}' file.
    CopyingDscResourceModules         = Expanding DSC resource modules to '{0}'.
    CopyingPowerShellModules          = Expanding PowerShell modules to '{0}'.
    WritingDvdProgress                = Writing DVD
    CreateDirectoryConfirmation       = Create Directory
    CopyFileConfirmation              = Copy File
    CopyExpandLabResourceConfirmation = Copy/Expand Resource
    CopyDscModulesConfirmation        = Copy DSC Resource Modules
    CopyPowerShellModulesConfirmation = Copy PowerShell Modules
    InstallDscResourcesConfirmation   = Install DSC Resource Modules
    InstallModulesConfirmation        = Install PowerShell Modules
    UsingVolumeName                   = Using volume name '{0}'.
    UsingScratchPath                  = Using scratch path '{0}'.
    UsingFilename                     = Using filename '{0}'.
    UsingOutputPath                   = Using output path '{0}'.
    DownloadingLabilityModules        = Downloading required Lability modules.
    DownloadingLabilityDscResources   = Downloading required Lability DSC resources.
    DownloadingLabilityResources      = Downloading required Lability binary resources.
    RemovingConfigurationDirectory    = Removing existing configuration directory '{0}'.
    CreatingConfigurationDirectory    = Creating configuration directory '{0}'.
    CreatingResourceDirectory         = Creating resource directory '{0}'.
    CopyingConfigurationBootstrap     = Copying bootstrap file '{0}'.
    CreatingDestinationDirectory      = Creating destination directory '{0}'.
    CreatingIsoRootDirectory          = Creating ISO root directory '{0}'.
    IsoFileCreatedIn                  = ISO file '{0}' created in '{1}'.

    GitNotFoundWarning                = GIT.EXE was not found.
    InvalidGitRepositoryWarning       = Path '{0}' is an invalid Git repository.

    InvalidDestinationPathError       = Invalid destination path '{0}' specified.
    NoFilenameDefinedError            = Resource '{0}' has no 'Filename' defined.
    ExpandNotSupportedError           = Expand operation not supported on '{0}' file type.
    InvalidConfigurationDataFileError = Invalid configuration data file '{0}'.
    InvalidConfigurationDataType      = Invalid configuration data type '{0}'.
    ResourceNotFoundError             = Resource '{0}' not found.
    CannotProcessCommandError         = Cannot process command because of one or more missing mandatory parameters: {0}.
    CannotBindArgumentError           = Cannot bind argument to parameter '{0}' because it is an empty string.
    InvalidDirectoryPathError         = Invalid directory path '{0}'.
    InvalidFileExtensionError         = File '{0}' is invalid. The file path should have the '{1}' extension.
    PathIsNotDirectoryError           = Path '{0}' is not a directory.
'@
